package com.example.projectserotonin.utils

object PrefUtils {
    const val DASHBOARD_API_FETCHED_FLAG = "DASHBOARD_API_FETCHED"
    const val REGIMEN_API_FETCHED_FLAG = "REGIMEN_API_FETCHED"
    const val DASHBOARD_RESPONSE = "DASHBOARD_RESPONSE"
    const val REGIMEN_ITEMS_TO_CONSUME = "REGIMEN_ITEMS_TO_CONSUME"
    const val IS_HOME_REFRESH_NEEDED = "IS_HOME_REFRESH_NEEDED"

}